name: Test
on:
  push:
    branches:
      - main
      - dev

jobs:
  typecheck:
    name: ʦ TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v5

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.4

      - name: 📥 Install pnpm
        run: npm install -g pnpm

      - name: 📥 Download deps
        run: pnpm install

      - name: 🔎 Type check
        run: pnpm run typecheck

  lint:
    name: ⬣ ESLint
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: "50"

      - name: 🛠 Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.4

      - name: 📥 Install pnpm
        run: npm install -g pnpm

      - name: 📥 Download deps
        run: pnpm install

      - name: 🔬 Lint
        run: pnpm run lint

  test-ci:
    name: Test CI
    runs-on: ubuntu-latest
    needs: [typecheck, lint]
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v5

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.4

      - name: 📥 Install pnpm
        run: npm install -g pnpm

      - name: 📥 Download deps
        run: pnpm install

      - name: Create Database Directory
        run: |
          mkdir -p db
          touch db/movies.sqlite

      - name: Install hurl
        run: pnpm add @orangeopensource/hurl

      - name: Run test
        env:
          DATABASE_URL: sqlite://db/movies.sqlite
          PLT_SERVER_LOGGER_LEVEL: info
          PORT: 3042
          PLT_SERVER_HOSTNAME: 127.0.0.1
        run: make test-ci
